meusite/AcervoDigital/urls.py
from . import views
from django.urls import path

app_name = "AcervoDigital"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('item/<int:pk>/', views.ItemView.as_view(), name='item'),
    path('lista', views.Listarlivros.as_view(), name='lista'),
    path('explorar', views.Listarlivros.as_view(), name='explorar'),
    path('cadastrarLivro/', views.LivroCreateView.as_view(), name='cadastrarLivro'),
    path('cadastrarContato/', views.ContatoCreateView.as_view(), name='cadastrarContato'),
    path('livro/<int:pk>/emprestar/', views.EmprestimoLivroView.as_view(), name='emprestarLivro'),
    path('registrar/', views.RegistroUsuarioView.as_view(), name='registrar'),
]

meusite/meusite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('raiz.urls')),
    path('enquetes/', include('enquetes.urls')),
    path('acervo/', include('AcervoDigital.urls')),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meusite/raiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

meusite/AcervoDigital/models.py
from django.db import models
from django.utils import timezone
from datetime import date
from django.contrib.auth.models import User, Group
from django.contrib.auth.forms import UserCreationForm

class Contato(models.Model):
    telefone = models.CharField(max_length=15)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=200)

    def __str__(self):
        return self.email

class Livro(models.Model):
    nome = models.CharField(max_length = 100)
    autor = models.CharField(max_length = 50)
    ano = models.DateField("Data de Publicação")
    imagem = models.ImageField(upload_to = 'media/')
    disponivel = models.BooleanField(default=True)
    contato = models.ForeignKey(Contato, null=True, blank=True, on_delete=models.SET_NULL)

meusite/AcervoDigital/models/contato.py
class Contato(models.Model):
    telefone = models.CharField(max_length=15)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=200)

    def __str__(self):
        return self.email

meusite/AcervoDigital/models/livro.py
class Livro(models.Model):
    nome = models.CharField(max_length = 100)
    autor = models.CharField(max_length = 50)
    ano = models.DateField("Data de Publicação")
    imagem = models.ImageField(upload_to = 'media/')
    disponivel = models.BooleanField(default=True)
    contato = models.ForeignKey(Contato, null=True, blank=True, on_delete=models.SET_NULL)

meusite/AcervoDigital/forms.py
from django import forms
from .models import Livro, Contato
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = ['nome', 'autor', 'ano', 'imagem']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do Livro'}),
            'autor': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Autor'}),
            'ano': forms.DateInput(attrs={'type': 'date', 'class': 'form-control', 'placeholder': 'Data de Publicação'}),
            'imagem': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

class EmprestimoLivroForm(forms.ModelForm):
    contato = forms.ModelChoiceField(queryset=Contato.objects.all(), required=True, label="Contato")

    class Meta:
        model = Livro
        fields = ['contato']
        widgets = {
            'contato': forms.Select(attrs={'class': 'form-control'}),
        }

class RegistroUsuarioForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome de Usuário'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Senha'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirme a Senha'}),
        }

class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ['email', 'telefone']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telefone'}),
        }

meusite/AcervoDigital/forms/ContatoForm.py
class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ['email', 'telefone']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telefone'}),
        }

meusite/AcervoDigital/forms/EmprestimoLivroForm.py
class EmprestimoLivroForm(forms.ModelForm):
    contato = forms.ModelChoiceField(queryset=Contato.objects.all(), required=True, label="Contato")

    class Meta:
        model = Livro
        fields = ['contato']
        widgets = {
            'contato': forms.Select(attrs={'class': 'form-control'}),
        }

meusite/AcervoDigital/forms/LivroForm.py
class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = ['nome', 'autor', 'ano', 'imagem']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do Livro'}),
            'autor': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Autor'}),
            'ano': forms.DateInput(attrs={'type': 'date', 'class': 'form-control', 'placeholder': 'Data de Publicação'}),
            'imagem': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

meusite/AcervoDigital/forms/RegistroUsuarioForm.py
class RegistroUsuarioForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome de Usuário'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Senha'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirme a Senha'}),
        }

meusite/AcervoDigital/views.py
from django.views import View
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView
from .forms import EmprestimoLivroForm, RegistroUsuarioForm, ContatoForm
from .forms import LivroForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from .models import Livro, Contato
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.urls import reverse_lazy


# Create your views here.

class IndexView(View):
    def get(self, request, *args, **kwargs):
        livros = Livro.objects.all()
        return render(request, "acervo/index.html", {'livros': livros})

class Listarlivros(View):
    def get(self, request, *args, **kwargs):
        livros = Livro.objects.all()
        livros_disp = Livro.objects.filter(disponivel=True)
        livros_indisp = Livro.objects.filter(disponivel=False)

        context = {
            'livros': livros,
            'livros_disp': livros_disp,
            'livros_indisp': livros_indisp,
            }
        return render(request, "acervo/listarLivros.html", context)

@method_decorator(login_required, name='dispatch')
class EmprestimoLivroView(UpdateView):
    model = Livro
    form_class = EmprestimoLivroForm
    template_name = 'emprestarLivro.html'
    success_url = reverse_lazy('AcervoDigital:index')

    def form_valid(self, form):
        livro = form.save(commit=False)
        livro.disponivel = False
        livro.save()
        contato = form.cleaned_data['contato']  # Pega o contato escolhido
        livro.contato = contato  # Associa o contato ao livro
        livro.save()
        messages.success(self.request, f'O livro "{livro.nome}" foi emprestado com sucesso!')
        return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class DevolverLivroView(View):
    def post(self, request, *args, **kwargs):
        livro_id = kwargs['pk']
        livro = get_object_or_404(Livro, pk = livro_id)
        livro.disponivel = True
        livro.contato_pessoal = None
        livro.save()
        return redirect("AcervoDigital:index")


## FORMS ##


class RegistroUsuarioView(CreateView):
    model = User
    form_class = RegistroUsuarioForm
    template_name = 'registrar.html'
    success_url = reverse_lazy('AcervoDigital:index')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        if user:
            login(self.request, user)
            messages.success(self.request, 'Cadastro realizado com sucesso!')
        return response

    def form_invalid(self, form):
        messages.error(self.request, 'Erro ao cadastrar. Por favor, verifique os dados.')
        return super().form_invalid(form)

@method_decorator(login_required, name='dispatch')
class LivroCreateView(CreateView):
    model = Livro
    form_class = LivroForm
    template_name = 'cadastrarLivro.html'
    success_url = reverse_lazy('AcervoDigital:index')

@method_decorator(login_required, name='dispatch')
class ContatoCreateView(CreateView):
    model = Contato
    form_class = ContatoForm
    template_name = 'cadastrarContato.html'
    success_url = reverse_lazy('AcervoDigital:index')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)

meusite/AcervoDigital/views/ContatoCreateView.py
@method_decorator(login_required, name='dispatch')
class ContatoCreateView(CreateView):
    model = Contato
    form_class = ContatoForm
    template_name = 'cadastrarContato.html'
    success_url = reverse_lazy('AcervoDigital:index')

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)

meusite/AcervoDigital/views/DevolverLivroView.py
@method_decorator(login_required, name='dispatch')
class DevolverLivroView(View):
    def post(self, request, *args, **kwargs):
        livro_id = kwargs['pk']
        livro = get_object_or_404(Livro, pk = livro_id)
        livro.disponivel = True
        livro.contato_pessoal = None
        livro.save()
        return redirect("AcervoDigital:index")

meusite/AcervoDigital/views/EmprestimoLivroView.py
@method_decorator(login_required, name='dispatch')
class EmprestimoLivroView(UpdateView):
    model = Livro
    form_class = EmprestimoLivroForm
    template_name = 'emprestarLivro.html'
    success_url = reverse_lazy('AcervoDigital:index')

    def form_valid(self, form):
        livro = form.save(commit=False)
        livro.disponivel = False
        livro.save()
        contato = form.cleaned_data['contato']  # Pega o contato escolhido
        livro.contato = contato  # Associa o contato ao livro
        livro.save()
        messages.success(self.request, f'O livro "{livro.nome}" foi emprestado com sucesso!')
        return super().form_valid(form)

meusite/AcervoDigital/views/ListarLivros.py
class Listarlivros(View):
    def get(self, request, *args, **kwargs):
        livros = Livro.objects.all()
        livros_disp = Livro.objects.filter(disponivel=True)
        livros_indisp = Livro.objects.filter(disponivel=False)

        context = {
            'livros': livros,
            'livros_disp': livros_disp,
            'livros_indisp': livros_indisp,
            }
        return render(request, "acervo/listarLivros.html", context)

meusite/AcervoDigital/views/LivroCreateView.py
@method_decorator(login_required, name='dispatch')
class LivroCreateView(CreateView):
    model = Livro
    form_class = LivroForm
    template_name = 'cadastrarLivro.html'
    success_url = reverse_lazy('AcervoDigital:index')

meusite/AcervoDigital/views/RegistroUsuarioView.py
class RegistroUsuarioView(CreateView):
    model = User
    form_class = RegistroUsuarioForm
    template_name = 'registrar.html'
    success_url = reverse_lazy('AcervoDigital:index')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        if user:
            login(self.request, user)
            messages.success(self.request, 'Cadastro realizado com sucesso!')
        return response

    def form_invalid(self, form):
        messages.error(self.request, 'Erro ao cadastrar. Por favor, verifique os dados.')
        return super().form_invalid(form)

meusite/AcervoDigital/views/indexView.py
class IndexView(View):
    def get(self, request, *args, **kwargs):
        livros = Livro.objects.all()
        return render(request, "acervo/index.html", {'livros': livros})

meusite/AcervoDigital/templates/acervo/index.html
{% extends 'base.html' %}

{% block title %}AcervoDigital{% endblock %}

{% block content %}
<h2>Bem vindo ao Acervo Digital, {{ user.username }}!</h2>

<h2>Livros Registrados</h3>

<ul class="container_livros">
    <container>
        {% for livro in livros %}
        <li class="livro">
            <img src="{{ livro.imagem.url }}" alt="{{ livro.nome }}" style="max-width: 200px;">
            <h3>{{ livro.nome }}</h3>
            <p>Autor: {{ livro.autor }}</p>
            <p style="font-size: 12px;">Ano: {{ livro.ano }}</p>
            {% if livro.disponivel %}
                <a href="{% url 'AcervoDigital:emprestarLivro' livro.id %}" class="btn">Pegar Emprestado</a>
            {% else %}
                <button class="btn-danger"> Indisponível</button>
                <p>(emprestado para {{ livro.contato }})</p>
            {% endif %}
        </li>
        {% empty %}
        <li>Não há livros registrados.</li>
        {% endfor %}
    </container>
</ul>


    {% endblock %}

meusite/AcervoDigital/templates/acervo/listarLivros.html
{% extends 'base.html' %}


{% block content %}

<h2>Livros Registrados</h2>
<div style="text-align: center; ">
    <a href="#disponiveis" class="btn" style="margin-right: 15px;">Livros Disponíveis</a>
    <a href="#indisponiveis" class="btn-danger">Livros Indisponíveis</a>
</div>

<ul class="container_livros">
    <container>
        {% for livro in livros %}
        <li class="livro">
            <img src="{{ livro.imagem.url }}" alt="{{ livro.nome }}" style="max-width: 200px;">
            <h3>{{ livro.nome }}</h3>
            <p>Autor: {{ livro.autor }}</p>
            <p style="font-size: 12px;">Ano: {{ livro.ano }}</p>
            {% if livro.disponivel %}
                <a href="{% url 'AcervoDigital:emprestarLivro' livro.id %}" class="btn">Pegar Emprestado</a>
            {% else %}
                <button class="btn-danger"> Indisponível</button>
                <p>(emprestado para {{ livro.contato }})</p>
            {% endif %}
        </li>
        {% empty %}
        <li>Não há livros registrados.</li>
        {% endfor %}
    </container>
</ul>
<h2 id="disponiveis">Livros Disponíveis</h2>
<ul class="container_livros">
    <container>
        {% for livro_disp in livros_disp %}
        <li class="livro">
            <img src="{{ livro_disp.imagem.url }}" alt="{{ livro_disp.nome }}" style="max-width: 200px;">
            <h3>{{ livro_disp.nome }}</h3>
            <p>Autor: {{ livro_disp.autor }}</p>
            <p style="font-size: 12px;">Ano: {{ livro_disp.ano }}</p>
            {% if livro_disp.disponivel %}
                <a href="{% url 'AcervoDigital:emprestarLivro' livro_disp.id %}" class="btn">Pegar Emprestado</a>
            {% else %}
                <button class="btn-danger"> Indisponivel</button>
                <p>(emprestado para {{ livro_disp.contato }})</p>
            {% endif %}
        </li>
        {% empty %}
        <li>Não há livros registrados.</li>
        {% endfor %}
    </container>
</ul>
<h2 id="indisponiveis">Livros Indisponiveis</h2>
<ul class="container_livros">
    <container>
        {% for livro in livros_indisp %}
        <li class="livro">
            <img src="{{ livro.imagem.url }}" alt="{{ livro.nome }}" style="max-width: 200px;">
            <h3>{{ livro.nome }}</h3>
            <p>Autor: {{ livro.autor }}</p>
            <p style="font-size: 12px;">Ano: {{ livro.ano }}</p>
            {% if livro.disponivel %}
                <a href="{% url 'AcervoDigital:emprestarLivro' livro.id %}" class="btn">Pegar Emprestado</a>
            {% else %}
                <button class="btn-danger"> Indisponível</button>
                <p>(emprestado para {{ livro.contato }})</p>
            {% endif %}
        </li>
        {% empty %}
        <li>Não há livros registrados.</li>
        {% endfor %}
    </container>
</ul>
{% endblock %}