meusite/enquetes/urls.py
from django.urls import path
from . import views

app_name = 'enquetes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetalhesView.as_view(), name='detalhes'),
    path('<int:pk>/resultado/', views.ResultadoView.as_view(), name='resultado'),
    path('<int:pergunta_id>/votacao', views.votacao, name='votacao'),


]
    # URL "/enquetes/" --> lista geral das enquetes
    # URL "/enquetes/5/" --> detalhes da enquete com "id" 5
    # URL "/enquetes/5/resultados" --> resultados da enquete com "id" 5
    # URL "/enquetes/5/votacao" --> votacao da enquete com "id" 5

meusite/meusite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('raiz.urls')),
    path('enquetes/', include('enquetes.urls')),
    path('acervo/', include('AcervoDigital.urls')),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meusite/raiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

meusite/enquetes/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.

class Pergunta(models.Model):
    texto_pergunta = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField('Data de Publicação')
    def __str__(self):
        return self.texto_pergunta
    def foi_publicado_recentemente(self):
        return self.data_publicacao >= timezone.now() - datetime.timedelta(days=1)
    foi_publicado_recentemente.admin_order_field = 'data_publicacao'
    foi_publicado_recentemente.boolean = True
    foi_publicado_recentemente.short_description = 'É recente?'


class Alternativa(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete =models.CASCADE)
    texto_alternativa = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    def __str__(self):
        return '{} ({})'.format(self.texto_alternativa, self.id)

meusite/enquetes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Pergunta, Alternativa
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'enquetes/index.html'
    def get_queryset(self):
        return Pergunta.objects.order_by('-data_publicacao') [:10]

class DetalhesView(generic.DetailView):
    model = Pergunta
    template_name = 'enquetes/detalhes.html'

class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'enquetes/resultado.html'

def votacao(request, pergunta_id):
     pergunta = get_object_or_404(Pergunta, pk = pergunta_id)
     try:
         id_alternativa = request.POST['escolha']
         alt = pergunta.alternativa_set.get(pk=id_alternativa)
     except (KeyError, Alternativa.DoesNotExist):
         contexto = {
             'pergunta': pergunta,
             'error': 'Você precisa selecionar uma alternativa.'
         }
         return render(request, 'enquetes/detalhes.html', contexto)
     else:
        alt.votos += 1
        alt.save()
        return HttpResponseRedirect(
            reverse( 'enquetes:resultado', args=(pergunta_id,))
            )

####
## HISTÓRICO DE VERSÕES
"""
----> View INDEX - Versão 1
def index(request):
    enquetes = Pergunta.objects.all()
    template = loader.get_template('enquetes/index.html')
    contexto = {'lista_enquetes': lista_ultima_pergunta}
    return HttpResponse(template.render(contexto, request))
---> View DETALHES - Versão 1
def detalhes(request, pergunta_id):
    resultado = 'DETALHES da enquete de número %s'
    return HttpResponse(resultado % pergunta_id)

---> View INDEX - Versão 2
def index(request):
    lista_ultima_pergunta = Pergunta.objects.order_by('-data_publicacao') [:10]
    contexto = {'lista_ultima_pergunta': lista_ultima_pergunta}
    return render(request, 'enquetes/index.html', contexto)

---> View DETALHES - Versão 2
def detalhe(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk = pergunta_id)
    contexto = {'enquete' : pergunta}
    return render(request, 'enquetes/detalhe.html', contexto)


---> View RESULTADOS - Versão 2
def resultados(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk = pergunta_id)
    contexto = {'enquete' : pergunta}
    return render(request, 'enquetes/resultado.html', contexto)
"""

meusite/enquetes/templates/enquetes/detalhe.html
<html>
    <head>
        <title>App Enquetes</title>
    </head>
    <body>
        <h1>Aplicação de Enquetes - DSWeb 2024.1</h1>
        <h2>Enquete #{{ enquete.id }}</h2>
        <h2>{{ enquete.texto_pergunta }}</h2>
        <p><i>{{ enquete.data_publicacao }}</i></p>
        {% if error%}
        <dt><b>Erro: {{ error }}</b></dt>
        {% endif %}
        <p>Selecione a alternativa</p>
        <form action = "{% url 'enquetes:votacao' enquete.id %}"
              method="post">
            {% csrf_token %}
        <ul>
            {% for alt in enquete.alternativa_set.all %}
            <li>
                <input type="radio" name="escolha" value="{{ alt.id }}"
                    id="alt{{ forloop.counter }}"/>
                <label for="alt{{ forloop.counter }}">
                    {{ alt.texto_alternativa }}
                </label>
            </li>
            {% endfor %}
        </ul>
        <input type="submit" value="Registre seu voto">
        </form>
        <hr>
        <a href="{% url 'enquetes:index' %}">Voltar</a>
    </body>
</html>

meusite/enquetes/templates/enquetes/detalhes.html
{% load static %}
<html>
    <head>
        <title>App Enquetes</title>
    </head>
    <link rel="stylesheet" type="text/css" href="{% static 'enquetes/style.css' %}">
    <body>
        <h1>Aplicação de Enquetes - DSWeb 2024.1</h1>
        <h2>Enquete #{{ pergunta.id }}</h2>
        <h2>{{ pergunta.texto_pergunta }}</h2>
        <p><i>{{ pergunta.data_publicacao }}</i></p>
        {% if error%}
        <dt><b>Erro: {{ error }}</b></dt>
        {% endif %}
        <p>Selecione a alternativa</p>
         <form action="{% url 'enquetes:votacao' pergunta.id %}"
            method="post">
            {% csrf_token %}
        <ul>
            {% for alt in pergunta.alternativa_set.all %}
            <li>
                <input type="radio" name="escolha" value="{{ alt.id }}"
                    id="alt{{ forloop.counter }}"/>
                <label for="alt{{ forloop.counter }}">
                    {{ alt.texto_alternativa }}
                </label>
            </li>
            {% endfor %}
        </ul>
        <input type="submit" id = "value" value="Registre seu voto">
        </form>
        <hr>
        <a href="{% url 'enquetes:index' %}"><b>Voltar</b></a>
    </body>
</html>

meusite/enquetes/templates/enquetes/index.html
    {% load static %}
<html>
    <head>
        <title>App Enquetes</title>
    </head>

    <link rel="stylesheet" type="text/css" href="{% static 'enquetes/style.css' %}">
    <body>
        <h1>Aplicação de <u>Enquetes</u></h1> <h2>Matéria: <u>DSWeb</u></h2> <h2>Semestre: <u>2024.1</u></h2> <h2>Nome do aluno: <u>Victor Paiva Passos</u></h2> <h2>Matrícula: <u>20231014040042</u></h2>
    {% if pergunta_list %}
    <h2>Lista das Enquetes Cadastradas:</h2>
    <ul>
        {% for pergunta in pergunta_list %}
        <li>
            <a href="{% url 'enquetes:detalhes' pergunta.id %}">
                {{ pergunta.texto_pergunta }}
            </a>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Nenhuma questão disponível.</p>
{% endif %}
    </body>
</html>

meusite/enquetes/templates/enquetes/resultado.html
{% load static %}
<html>
    <head>
        <title>App Enquetes</title>
    </head>
    <link rel="stylesheet" type="text/css" href="{% static 'enquetes/style.css' %}">
    <body>
        <h1>Resultado da enquete - DSWeb 2024.1</h1>
        <h2>Enquete #{{ pergunta.id }}</h2>
        <h3>Seu voto foi computado! Obrigado!</h3>
        <h2>{{ pergunta.texto_pergunta }}</h2>
        <p><i>{{ pergunta.data_publicacao }}</i></p>
        {% if error%}
        <dt><b>Erro: {{ error }}</b></dt>
        {% endif %}
        <p>Quantidade de votos por alternativas:</p>
        <ul>
            {% for alt in pergunta.alternativa_set.all %}
            <li>{{ alt.texto_alternativa }} = {{ alt.votos }}
                voto{{ alt.votos | pluralize }}
            </li>
            {% endfor %}
        </ul>
        <hr>
        <a href="{% url 'enquetes:votacao' pergunta.id %}"><b>Votar Novamente</b></a>
        <a href="{% url 'enquetes:index' %}"><b>Voltar</b></a>
    </body>
</html>